repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: [--fix, --show-fixes]
-   repo: https://github.com/samueljsb/sort-lines
    rev: v0.3.0
    hooks:
    -   id: sort-lines
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: trailing-whitespace
