name: CI

on:
  pull_request:
  push:
    branches: [main]

# Only allow one instance of this workflow for each PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: |
          3.10
          3.11
          3.12
          3.13
        allow-prereleases: true
    - run: python -m pip install tox
    - run: tox run-parallel --parallel-no-spinner
      env:
        FORCE_COLOR: true

  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    # pip currently cannot install dependency groups,
    # so we rely on nox to do that for us.
    - run: python -m pip install nox
    - run: nox -s mypy
      env:
        FORCE_COLOR: true
